export const copy = {
  productName: "Jimin OS",
  scope: "개인 서버",
  actions: {
    checkAgain: "다시 확인하기",
    checkAgainLabel: "서버 상태 다시 확인하기",
    checking: "확인하고 있어요",
    refresh: "새로고침",
    addTask: "할 일 추가하기",
    addSchedule: "일정 추가하기",
    complete: "완료하기",
    startConversation: "새 요청",
    sendRequest: "보내기",
    sendingRequest: "보내는 중",
    connectChatgpt: "ChatGPT 연결하기",
    retryChatgptConnection: "다시 연결하기",
    openChatgpt: "브라우저에서 ChatGPT 열기",
    copyAuthenticationCode: "코드 복사하기",
    retryPersonalServer: "다시 연결하기",
  },
  summary: {
    checkingTitle: "서버 상태를 확인하고 있어요",
    checkingBody: "현재 연결 상태를 불러오는 중이에요.",
    readyTitle: "서버에 연결됐어요",
    readyBody: "개인 서버의 데이터를 사용할 준비가 됐어요.",
    attentionTitle: "서버 준비가 더 필요해요",
    attentionBody: "필요한 항목을 확인한 뒤 다시 시도해 주세요.",
    disconnectedTitle: "서버에 연결하지 못했어요",
    disconnectedBody:
      "개인 서버 실행 상태와 네트워크 연결을 확인한 뒤 다시 시도해 주세요.",
  },
  checks: {
    ready: "준비됨",
    attention: "확인 필요",
    disconnected: "연결 안 됨",
  },
  configuration: {
    eyebrow: "Jimin OS 설정 확인",
    title: "개인 서버 정보를 찾을 수 없어요",
    description: "이 설치본에 개인 서버 정보가 포함되지 않았어요.",
    nextTitle: "서버 주소를 직접 입력할 필요는 없어요",
    nextDescription:
      "개인 서버가 포함된 설치본으로 다시 설치해 주세요.",
  },
  personalServer: {
    title: "개인 서버에 연결하지 못했어요",
    deviceName: "Jimin OS",
  },
  schedule: {
    title: "다가오는 일정",
    description: "앞으로 7일 동안의 일정이에요.",
    empty: "아직 등록한 일정이 없어요. 필요한 시간을 먼저 잡아 보세요.",
  },
  tasks: {
    title: "열린 할 일",
    description: "완료하지 않은 일을 우선순위대로 보여줘요.",
    empty: "열린 할 일이 없어요. 다음에 할 일을 추가해 보세요.",
  },
  conversations: {
    identity: "Jimin, 개인 AI 비서",
    title: "무엇을 도와드릴까요?",
    description: "일정, 생각, 해야 할 일을 말하듯이 적어 주세요.",
    startersLabel: "요청 예시",
    starters: [
      "내일 해야 할 일을 정리해 줘",
      "이번 주에 놓치면 안 되는 일을 알려 줘",
      "지금 고민 중인 일을 같이 정리해 줘",
    ],
    listTitle: "대화 기록",
    listDescription: "이전 대화를 이어서 볼 수 있어요.",
    newConversation: "새 요청",
    untitled: "이름 없는 대화",
    noMessages: "아직 내용이 없어요",
    empty: "이전 대화가 여기에 보여요.",
    threadDescription: "요청과 결과를 한곳에서 이어서 볼 수 있어요.",
    threadEmpty: "아직 주고받은 내용이 없어요. 지금 필요한 일을 적어 보세요.",
    userLabel: "나",
    composerLabel: "Jimin에게 메시지 보내기",
    composerPlaceholder: "예: 내일 오후 2시에 운동 일정 잡아 줘",
    composerHelp: "한 번에 하나의 요청을 처리해요.",
    preparing: "요청을 준비하고 있어요.",
    processing: "요청을 처리하고 있어요.",
    waitingApproval: "승인이 필요한 작업을 확인하고 있어요.",
    failed: "요청을 완료하지 못했어요. 내용을 확인한 뒤 다시 보내 주세요.",
  },
  authentication: {
    title: "ChatGPT를 연결하면 바로 대화를 시작할 수 있어요.",
    description:
      "한 번 연결하면 이 기기와 다른 기기에서 같은 대화를 이어갈 수 있어요.",
    prepareTitle: "ChatGPT 연결을 준비하고 있어요.",
    prepareDescription: "잠시 후 ChatGPT에서 입력할 연결 코드가 표시돼요.",
    preparing: "연결 코드를 준비하고 있어요.",
    awaitingTitle: "ChatGPT에서 연결을 마쳐 주세요.",
    awaitingDescription:
      "시스템 브라우저에서 ChatGPT를 연 뒤 아래 코드를 입력해 주세요. 완료되면 이 앱에서 자동으로 대화를 시작할 수 있어요.",
    codeLabel: "연결 코드",
    copiedCode: "코드를 복사했어요",
    browserOpenFailed: "브라우저를 열지 못했어요. 다시 시도해 주세요.",
    failedTitle: "ChatGPT 연결을 시작하지 못했어요. 다시 시도해 주세요.",
    recoveryDescription: "문제가 계속되면 앱을 다시 열어 주세요.",
  },
  forms: {
    taskTitle: "할 일 추가",
    taskLabel: "할 일",
    scheduleTitle: "일정 추가",
    scheduleLabel: "일정 이름",
    startsAt: "시작 시간",
    endsAt: "종료 시간",
  },
  messages: {
    personalServerUnavailable: "VPN 연결과 개인 서버 상태를 확인한 뒤 다시 시도해 주세요.",
    loadFailed: "계획을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    saveFailed: "변경 내용을 저장하지 못했어요. 다시 시도해 주세요.",
    taskAdded: "할 일을 추가했어요.",
    taskCompleted: "할 일을 완료했어요.",
    taskChanged:
      "할 일이 다른 기기에서 변경됐어요. 새로고침 후 다시 확인해 주세요.",
    scheduleAdded: "일정을 추가했어요.",
    conversationLoadNotice:
      "대화를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    conversationSendNotice:
      "요청을 보내지 못했어요. 내용을 확인한 뒤 다시 시도해 주세요.",
    conversationBusy:
      "이 요청을 처리하고 있어요. 끝난 뒤 새 요청을 보낼 수 있어요.",
    conversationChanged:
      "다른 기기에서 대화가 변경됐어요. 대화 목록을 다시 확인해 주세요.",
    authenticationLoadNotice:
      "ChatGPT 연결 상태를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    authenticationStartNotice:
      "ChatGPT 연결을 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
    authenticationRequired: "ChatGPT 계정을 연결한 뒤 메시지를 보낼 수 있어요.",
  },
} as const;
