const settingsTab = "설정";

export const copy = {
  productName: "Jimin OS",
  scope: "개인 서버",
  launch: {
    loading: "개인 비서를 준비하고 있어요.",
  },
  actions: {
    checkAgain: "다시 확인하기",
    checkAgainLabel: "서버 상태 다시 확인하기",
    checking: "확인하고 있어요",
    refresh: "새로고침",
    addTask: "할 일 추가하기",
    addSchedule: "일정 추가하기",
    complete: "완료하기",
    startConversation: "새 요청",
    sendRequest: "보내기",
    sendingRequest: "보내는 중",
    retryRequest: "다시 보내기",
    connectChatgpt: "ChatGPT 연결하기",
    retryChatgptConnection: "다시 연결하기",
    openChatgpt: "브라우저에서 ChatGPT 열기",
    copyAuthenticationCode: "코드 복사하기",
    retryPersonalServer: "다시 연결하기",
    goHome: "나의 하루로 가기",
    startAssistantConversation: "지민에게 말하기",
    openConversation: "대화 열기",
    viewSchedule: "일정 보기",
    viewMemory: "기억 보기",
    approveAction: "실행하기",
    declineAction: "취소",
  },
  navigation: {
    label: "Jimin OS 탐색",
    home: "나의 하루",
    mobileHome: "홈",
    schedule: "일정",
    chat: "채팅",
    memory: "기억",
    settings: settingsTab,
    assistant: "지민",
  },
  home: {
    commandPlaceholder: "무엇이든 물어보거나 시켜보세요",
    morningGreeting: "좋은 아침이에요!",
    afternoonGreeting: "좋은 오후예요",
    eveningGreeting: "오늘도 수고했어요",
    title: "지민에게 말만 하면 제가 처리해둘게요.",
    description: "오늘 일정과 할 일을 먼저 정리해 볼게요.",
    briefingLabel: "아침 브리핑",
    askAssistant: "지민에게 말하기",
    connectAssistant: "ChatGPT 연결하기",
    loadingBriefing: "오늘 정보를 불러오고 있어요",
    loadingDescription: "일정과 할 일을 확인하는 중이에요.",
    briefingWithNext: (title: string) => `다음은 ${title} 일정이에요`,
    briefingWithSchedule: (count: number) => `오늘 일정이 ${count}개 있어요`,
    briefingEmpty: "오늘은 비어 있는 시간부터 시작해 볼까요?",
    briefingTaskCount: (count: number) =>
      count
        ? `열린 할 일 ${count}개도 함께 정리해 드릴게요.`
        : "지금은 일정에 집중하면 돼요.",
    briefingOnlyTasks: (count: number) => `열린 할 일 ${count}개가 있어요.`,
    briefingNoItems: "아직 등록한 일정이나 할 일이 없어요.",
    scheduleTitle: "오늘 일정",
    scheduleCount: (count: number) => `${count}개`,
    scheduleEmptyTitle: "오늘 일정이 없어요",
    scheduleEmptyDescription: "필요한 시간을 비서에게 말해 보세요.",
    taskTitle: "오늘 할 일",
    taskCount: (count: number) => `${count}개`,
    taskEmptyTitle: "열린 할 일이 없어요",
    taskEmptyDescription: "지금 해야 할 일을 비서에게 적어 보세요.",
    completeTask: (title: string) => `${title} 완료하기`,
    nextActionLabel: "다음 행동",
    nextActionSchedule: (title: string) => `${title} 준비를 같이 시작할까요?`,
    nextActionEmpty: "비어 있는 시간을 어떻게 쓸지 비서와 정해 보세요.",
    openAssistant: "비서 열기",
    assistantRailTitle: "지민",
    assistantReady: "오늘의 맥락을 바탕으로 함께 정리할 수 있어요.",
    assistantNeedsConnection:
      "ChatGPT를 연결하면 대화를 바로 시작할 수 있어요.",
    assistantPrompt: "지민에게 말하기",
    loadingShort: "불러오는 중",
  },
  summary: {
    checkingTitle: "서버 상태를 확인하고 있어요",
    checkingBody: "현재 연결 상태를 불러오는 중이에요.",
    readyTitle: "서버에 연결됐어요",
    readyBody: "개인 서버의 데이터를 사용할 준비가 됐어요.",
    attentionTitle: "서버 준비가 더 필요해요",
    attentionBody: "필요한 항목을 확인한 뒤 다시 시도해 주세요.",
    disconnectedTitle: "서버에 연결하지 못했어요",
    disconnectedBody:
      "개인 서버 실행 상태와 네트워크 연결을 확인한 뒤 다시 시도해 주세요.",
  },
  checks: {
    ready: "준비됨",
    attention: "확인 필요",
    disconnected: "연결 안 됨",
  },
  configuration: {
    eyebrow: "Jimin OS 설정 확인",
    title: "개인 서버 정보를 찾을 수 없어요",
    description: "이 설치본에 개인 서버 정보가 포함되지 않았어요.",
    nextTitle: "서버 주소를 직접 입력할 필요는 없어요",
    nextDescription: "개인 서버가 포함된 설치본으로 다시 설치해 주세요.",
  },
  personalServer: {
    title: "개인 서버에 연결하지 못했어요",
    deviceName: "Jimin OS",
  },
  schedule: {
    title: "일정",
    description: "오늘 해야 할 일과 일정을 한곳에서 확인해요.",
    empty: "아직 등록한 일정이 없어요. 필요한 시간을 먼저 잡아 보세요.",
  },
  tasks: {
    title: "열린 할 일",
    description: "완료하지 않은 일을 우선순위대로 보여줘요.",
    empty: "열린 할 일이 없어요. 다음에 할 일을 추가해 보세요.",
  },
  memory: {
    title: "기억",
    description: "대화에서 남길 내용을 직접 고르고 다시 확인할 수 있어요.",
    emptyTitle: "아직 저장한 기억이 없어요",
    emptyDescription:
      "대화에서 남기고 싶은 내용을 정하면 여기에 모아둘 수 있어요.",
    openConversation: "대화로 내용 정리하기",
  },
  voice: {
    closeLabel: "음성 명령 시트 닫기",
    listeningTitle: "듣고 있어요",
    listeningDescription: "말을 마치면 내용을 확인할 수 있어요.",
    listeningHint:
      "“내일 오후 3시에 치과 일정 등록해 줘” · “내일 일정 알려 줘” · “할 일에 장보기 추가해 줘”",
    finalizingTitle: "말한 내용을 정리하고 있어요",
    finalizingDescription: "잠시만 기다려 주세요.",
    finalizingAction: "내용 확인 중",
    heardTitle: "말씀하신 내용을 처리하고 있어요",
    heardDescription: "일정과 할 일을 확인하고 있어요.",
    noSpeechTitle: "말한 내용을 듣지 못했어요",
    noSpeechDescription: "조금 더 가까이에서 또렷하게 말해 주세요.",
    voiceTitle:
      "음성 인식을 시작하지 못했어요. 다시 말하거나 입력으로 이어가 주세요.",
    voiceDescription: "마이크 권한과 기기 설정을 확인해 주세요.",
    permissionRecovery:
      "마이크 권한을 허용한 뒤 다시 말하거나 입력으로 이어가 주세요.",
    speechFallback:
      "말한 내용을 듣지 못했어요. 다시 말하거나 입력으로 이어가 주세요.",
    fallbackRecovery:
      "이 기기에서 음성 인식을 사용할 수 없어요. 입력으로 이어가 주세요.",
    retry: "다시 말하기",
    finishListening: "말하기 마치기",
    useTranscript: "대화에서 확인하기",
    processingCommandTitle: "말씀하신 내용을 처리하고 있어요",
    processingCommandDescription: "일정과 할 일을 확인하고 있어요.",
    processingCommandAction: "처리 중",
    commandHandledTitle: "처리했어요",
    commandNeedsDetailsTitle: "조금 더 알려 주세요",
    commandConversationTitle: "대화에서 이어서 도와드릴게요",
    commandFailedTitle: "처리하지 못했어요. 다시 말해 주세요",
    commandFailed: "잠시 후 다시 말하거나 입력으로 이어가 주세요.",
    openHome: "오늘에서 확인하기",
    openSchedule: "일정에서 확인하기",
    continueConversation: "대화에서 이어가기",
    useTextInput: "입력으로 이어가기",
    close: "닫기",
  },
  settings: {
    title: settingsTab,
    description: "지민이 사용할 연결 상태를 확인할 수 있어요.",
    chatgptTitle: "ChatGPT 연결",
    chatgptReady: "연결되어 있어요",
    chatgptNeedsLogin: "연결이 필요해요",
    chatgptPreparing: "연결을 준비하고 있어요",
    chatgptAwaiting: "ChatGPT에서 연결을 마쳐 주세요",
    chatgptFailed: "연결을 다시 확인해 주세요",
  },
  conversations: {
    identity: "지민",
    mobileDescription: "개인 비서",
    title: "무엇을 함께 정리할까요?",
    description: "오늘 필요한 일이나 고민을 편하게 말해 주세요.",
    startersLabel: "이렇게 시작해 보세요",
    starters: ["내일 해야 할 일을 정리해 줘", "이번 주 일정을 함께 정리해 줘"],
    listTitle: "최근 대화",
    listDescription: "이전 대화를 이어서 볼 수 있어요.",
    newConversation: "새 대화",
    untitled: "이름 없는 대화",
    noMessages: "아직 내용이 없어요",
    empty: "완료된 대화가 생기면 여기에 보여요.",
    threadEyebrow: "대화",
    threadDescription: "요청과 결과를 한곳에서 이어서 볼 수 있어요.",
    threadEmpty: "아직 주고받은 내용이 없어요. 지금 필요한 일을 적어 보세요.",
    userLabel: "나",
    composerLabel: "비서에게 메시지 보내기",
    composerPlaceholder: "무엇이든 말해 보세요",
    composerHelp: "일정, 할 일, 메모를 말하듯이 적어 보세요.",
    preparing: "요청을 준비하고 있어요.",
    processing: "답변을 작성하고 있어요.",
    streaming: "답변 작성 중",
    waitingApproval: "승인이 필요한 작업을 확인하고 있어요.",
    approvalEyebrow: "실행 확인",
    approvalTitle: "이 작업을 실행할까요?",
    approvalTaskDescription: "{title} 할 일을 추가해요.",
    approvalScheduleDescription: "{title} 일정을 등록해요.",
    approvalScheduleWithTime: "{time}에 {title} 일정을 등록해요.",
    failed: "답변을 만들지 못했어요. 다시 보내 주세요.",
    failedDescription: "내용을 조금 바꿔서 다시 보내도 돼요.",
  },
  authentication: {
    title: "ChatGPT를 연결하면 바로 대화를 시작할 수 있어요.",
    description:
      "한 번 연결하면 이 기기와 다른 기기에서 같은 대화를 이어갈 수 있어요.",
    prepareTitle: "ChatGPT 연결을 준비하고 있어요.",
    prepareDescription: "잠시 후 ChatGPT에서 입력할 연결 코드가 표시돼요.",
    preparing: "연결 코드를 준비하고 있어요.",
    awaitingTitle: "ChatGPT에서 연결을 마쳐 주세요.",
    awaitingDescription:
      "시스템 브라우저에서 ChatGPT를 연 뒤 아래 코드를 입력해 주세요. 완료되면 이 앱에서 자동으로 대화를 시작할 수 있어요.",
    codeLabel: "연결 코드",
    copiedCode: "코드를 복사했어요",
    browserOpenFailed: "브라우저를 열지 못했어요. 다시 시도해 주세요.",
    failedTitle: "ChatGPT 연결을 시작하지 못했어요. 다시 시도해 주세요.",
    recoveryDescription: "문제가 계속되면 앱을 다시 열어 주세요.",
  },
  forms: {
    taskTitle: "할 일 추가",
    taskLabel: "할 일",
    scheduleTitle: "일정 추가",
    scheduleLabel: "일정 이름",
    startsAt: "시작 시간",
    endsAt: "종료 시간",
  },
  messages: {
    serverOffline: "VPN 연결과 개인 서버 상태를 확인한 뒤 다시 시도해 주세요.",
    homeLoadNotice:
      "오늘 정보를 불러오지 못했어요. 새로고침한 뒤 다시 확인해 주세요.",
    loadFailed: "계획을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    saveFailed: "변경 내용을 저장하지 못했어요. 다시 시도해 주세요.",
    taskAdded: "할 일을 추가했어요.",
    taskCompleted: "할 일을 완료했어요.",
    taskCompletionNotice:
      "할 일을 완료하지 못했어요. 현재 상태를 다시 불러온 뒤 시도해 주세요.",
    taskChanged:
      "할 일이 다른 기기에서 변경됐어요. 새로고침 후 다시 확인해 주세요.",
    scheduleAdded: "일정을 추가했어요.",
    conversationLoadNotice:
      "대화를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    conversationSendNotice:
      "요청을 보내지 못했어요. 연결을 다시 확인한 뒤 같은 요청을 보내 주세요.",
    conversationBusy:
      "이 요청을 처리하고 있어요. 끝난 뒤 새 요청을 보낼 수 있어요.",
    conversationChanged:
      "다른 기기에서 대화가 변경됐어요. 대화 목록을 다시 확인해 주세요.",
    actionResolutionNotice:
      "요청을 처리하지 못했어요. 대화를 다시 확인한 뒤 한 번 더 시도해 주세요.",
    authenticationLoadNotice:
      "ChatGPT 연결 상태를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    authenticationStartNotice:
      "ChatGPT 연결을 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
    authenticationRequired: "ChatGPT 계정을 연결한 뒤 메시지를 보낼 수 있어요.",
  },
} as const;
