export const projectCopy = {
  eyebrow: "업무 운영",
  title: "프로젝트",
  description: "개인과 회사의 일을 목적과 다음 행동으로 정리해요.",
  scopeLabel: "업무 범위 선택",
  createTitle: "새 프로젝트 만들기",
  createDescription: "목적과 바로 이어서 할 일을 함께 적어 두세요.",
  projectNameLabel: "프로젝트 이름",
  projectNameHint: "예: 월든페이 계약 등록 개선",
  objectiveLabel: "이 프로젝트에서 이루려는 일",
  objectiveHint: "완료했을 때 달라져야 하는 결과를 적어 보세요.",
  nextActionLabel: "지금 이어서 할 일",
  nextActionHint: "예: 계약 등록 화면의 흐름 정리하기",
  riskLabel: "현재 위험",
  riskLevels: ["안정적", "살펴볼 점", "일정 지연 가능", "바로 확인"],
  listTitle: "진행 중인 프로젝트",
  projectCount: (count: number) => `${count}개`,
  openTaskCount: (count: number) => `열린 일 ${count}개`,
  noNextAction: "다음 행동을 정해 보세요.",
  emptyTitle: "아직 프로젝트가 없어요",
  emptyDescription: "반복해서 챙길 일을 프로젝트로 묶어 보세요.",
  selectTitle: "프로젝트를 선택해 주세요",
  selectDescription: "다음 행동과 연결된 일을 한곳에서 볼 수 있어요.",
  objectiveEmpty: "이 프로젝트의 목표를 아직 적지 않았어요.",
  workItemsTitle: "지금 할 일",
  workItemsEmpty: "아직 연결된 일이 없어요. 바로 이어서 할 일을 추가해 보세요.",
  workItemLabel: "프로젝트에 추가할 일",
  workItemHint: "이 프로젝트에서 바로 할 일을 적어 보세요",
  titleRequired: "프로젝트 이름을 적어 주세요.",
  projectSaveNotice:
    "프로젝트를 저장하지 못했어요. 입력한 내용을 확인한 뒤 다시 시도해 주세요.",
  taskSaveNotice: "일을 추가하지 못했어요. 잠시 후 다시 시도해 주세요.",
} as const;
