export const projectCopy = {
  eyebrow: "업무 운영",
  title: "프로젝트",
  description: "개인과 회사의 일을 목적과 다음 행동으로 정리해요.",
  scopeLabel: "업무 범위 선택",
  createTitle: "새 프로젝트 만들기",
  createDescription: "목적과 바로 이어서 할 일을 함께 적어 두세요.",
  projectNameLabel: "프로젝트 이름",
  projectNameHint: "예: 월든페이 계약 등록 개선",
  objectiveLabel: "이 프로젝트에서 이루려는 일",
  objectiveHint: "완료했을 때 달라져야 하는 결과를 적어 보세요.",
  nextActionLabel: "지금 이어서 할 일",
  nextActionHint: "예: 계약 등록 화면의 흐름 정리하기",
  riskLabel: "현재 위험",
  riskLevels: ["안정적", "살펴볼 점", "일정 지연 가능", "바로 확인"],
  dueDateLabel: "마감일",
  noDueDate: "정하지 않음",
  statusLabel: "프로젝트 상태",
  currentStateLabel: "프로젝트 현재 상태",
  statuses: {
    active: "진행 중",
    paused: "잠시 멈춤",
    completed: "완료",
  },
  listTitle: "프로젝트 목록",
  projectCount: (count: number) => `${count}개`,
  openTaskCount: (count: number) => `열린 일 ${count}개`,
  noNextAction: "다음 행동을 정해 보세요.",
  emptyTitle: "아직 프로젝트가 없어요",
  emptyDescription: "반복해서 챙길 일을 프로젝트로 묶어 보세요.",
  selectTitle: "프로젝트를 선택해 주세요",
  selectDescription: "다음 행동과 연결된 일을 한곳에서 볼 수 있어요.",
  objectiveEmpty: "이 프로젝트의 목표를 아직 적지 않았어요.",
  projectDetailLabel: "프로젝트 현재 상태",
  editProject: "프로젝트 수정하기",
  editTitle: "프로젝트 수정",
  editDescription: "목표와 현재 상태, 다음 행동을 최신 내용으로 바꿔요.",
  stopEditing: "수정 그만두기",
  saveChanges: "변경 내용 저장하기",
  projectUpdated: "프로젝트를 최신 내용으로 바꿨어요.",
  projectUpdateNotice:
    "프로젝트를 바꾸지 못했어요. 최신 상태를 불러온 뒤 다시 시도해 주세요.",
  completedProjectNotice:
    "완료한 프로젝트에는 새 일을 추가하지 않아요. 다시 진행하려면 프로젝트 상태를 바꿔 주세요.",
  workItemsTitle: "지금 할 일",
  completedWorkItemsTitle: "완료한 일",
  completedTaskCount: (count: number) => `${count}개`,
  completedTaskMeta: (meta: string) => `완료 · ${meta}`,
  reopenTask: (title: string) => `${title} 다시 진행하기`,
  workItemsEmpty: "아직 연결된 일이 없어요. 바로 이어서 할 일을 추가해 보세요.",
  workItemLabel: "프로젝트에 추가할 일",
  workItemHint: "이 프로젝트에서 바로 할 일을 적어 보세요",
  editWorkItem: (title: string) => `${title} 내용 수정`,
  workItemTitleLabel: "일 이름",
  workItemTitleRequired: "일 이름을 적어 주세요.",
  workItemNotesLabel: "처리할 내용",
  workItemNotesHint: "완료 조건이나 확인할 내용을 적어 보세요.",
  workItemPriorityLabel: "우선순위",
  taskPriorities: ["낮음", "보통", "높음", "가장 먼저"],
  stopEditingWorkItem: "수정 그만두기",
  saveWorkItem: "일 내용 저장하기",
  removeWorkItem: "목록에서 지우기",
  keepWorkItem: "계속 보관하기",
  removeWorkItemConfirm:
    "이 일은 목록에서 사라지지만 변경 기록은 안전하게 보관해요. 지울까요?",
  taskUpdateNotice:
    "일을 바꾸지 못했어요. 최신 내용을 불러온 뒤 다시 시도해 주세요.",
  taskRemoveNotice:
    "일을 지우지 못했어요. 최신 내용을 불러온 뒤 다시 시도해 주세요.",
  titleRequired: "프로젝트 이름을 적어 주세요.",
  projectSaveNotice:
    "프로젝트를 저장하지 못했어요. 입력한 내용을 확인한 뒤 다시 시도해 주세요.",
  taskSaveNotice: "일을 추가하지 못했어요. 잠시 후 다시 시도해 주세요.",
} as const;
